// Generated from content/posts. Do not edit this file directly.

export const generatedPosts = [
  {
    "title": "The silent type",
    "slug": "a-pretty-normal-typeface",
    "date": "August 6, 2026",
    "readingTime": "2 minutes",
    "paragraphs": [
      "Untitled Sans began as an attempt to make another typeface plainer.",
      "Kris Sowersby removed some of its more noticeable details, got a little lost and put the project away, returned to it several years later, and nearly threw it out. Reading about the Super Normal project eventually helped him understand why a deliberately ordinary typeface might be worth finishing.",
      "I like that the reasoning came later. Design processes are often written up as though every decision followed neatly from the one before it. Mine rarely work that way. I try things. I change my mind. I forget why I started. Occasionally I end up with something useful.",
      "Sowersby describes removing traces of his own recognizable style from the letters. His goal wasn’t to make the typeface distinctive. It was to make something that could be successful without bringing a ton of baggage along with it.",
      "In design, as in life, that is extremely difficult to pull off. Designers are generally encouraged to—and take delight in—making things memorable. A plain typeface can feel like a missed opportunity. But most of the time I don’t need the type to be the most interesting thing on the page. I need it to help me read.",
      "That’s probably why Untitled Sans feels right for both my portfolio site and for this site. My work and my writing can wander around and follow unusual ideas. The letters stay put.",
      "Untitled Sans is very much a designed artifact. Its plainness is the result of a mountain of small, thoughtful, beautiful choices. It just doesn’t ask me to admire and praise those choices every time I read a paragraph.",
      "There is something deeply appealing to me about creating something that works so incredibly well without constantly advertising how much work went into it. Creating something that knows how to be quiet."
    ],
    "source": {
      "label": "Read Kris Sowersby’s notes on the Untitled Collection",
      "href": "https://klim.co.nz/blog/untitled-sans-serif-design-information/"
    }
  },
  {
    "title": "The utility of an empty mind",
    "slug": "the-usefulness-of-an-empty-mind",
    "date": "August 6, 2026",
    "readingTime": "3 minutes",
    "paragraphs": [
      "One of my favorite books—favorite manuals, really—is Zen Mind, Beginner's Mind, a book by the Zen monk Shunryu Suzuki.",
      "He says, “In the beginner’s mind there are many possibilities, in the expert’s, there are few.”",
      "Well, expertise is darn useful: it recognizes patterns, avoids old mistakes, it knows which details matter. But it can also become a kind of compression. The more I know about something, the less of it I may actually see. I see the category before I see the thing.",
      "Suzuki isn't telling us to strive for stupidity. Beginner’s mind isn't the absence of experience or knowledge. It's a way of standing in both without letting the shoes turn to cement. Easier said than done for sure.",
      "The book is assembled from talks and feels spoken. As you move through it, ideas appear, disappear, return slightly changed…sometimes an explanation leaves me less certain than when it began. Seems appropriate.",
      "He talks about posture, breathing, repetition, effort, and the ordinary difficulty of sitting still. The spiritual life he describes is visceral. It’s in my hands, my spine, my willingness to sit and practice without turning it into an achievement.",
      "But I like practices that produce results! I want to know whether I am progressing! Even when I’m actively trying to become less ambitious, I can become ambitious about becoming less ambitious.",
      "His advice is to return to the activity itself. Why sit? Because you are sitting. Breathe because you are breathing. Do the thing without constantly stepping outside it to decide what it means, what it means about you. I cannot say I consistently live this way, but I deeply respect and value the freedom in it.",
      "Beginner’s mind may be less about innocence than repeatedly setting down what I think I know. Not throwing it away, just…loosening my grip long enough for something else to appear.",
      "This book is not a manual for mastering Zen. It's a manual for taking aim at that part of me that wants to master it. Which makes it a manual for mastering Zen. Which makes it…",
      "This book does not make Zen easy.",
      "It does makes simplicity seem like enough for me to work on."
    ]
  },
  {
    "title": "The Odyssey",
    "slug": "remain-stranger",
    "date": "August 6, 2026",
    "readingTime": "2 minutes",
    "paragraphs": [
      "There’s a early scene in The Odyssey where Odyseuss is sitting with his mentor Eumaeus and examining a litter of puppies. Eumaeus picks one up and looks it over briefly before casually tossing it over the nearby ledge.",
      "Odysseus stops him from throwing the next one and keeps it for his own. And just like that, the scene goes from being shocking to being understandable again. We know who to identify with and how to feel.",
      "But for a hot minute, the film opens onto a stranger world. A world in which people live much, much closer to the reality of death. The borders between necessity, ritual, and cruelty are not where we expect them to be.",
      "I wanted the film to go there a little more often. When I encounter something unfamiliar, I tend to look for a known equivalent. A god becomes a psychological condition. A monster becomes trauma. A voyage becomes a metaphor for recovering from war. These translations give me ways into old stories like this one.",
      "Homer does not always allow that. His gods are vain, generous, jealous, horny, petty, and terrifying. They do not behave like symbols. Out of the millions years humans have been around, we have lived the vast majority of them beneath these forces without expecting the universe to be fair or particularly interested in being understood.",
      "While I am not really sure I would want to live inside that world, I am also not sure I want it sanitized for me. There may be value in letting an old thing remain old. In allowing its assumptions to sit beside mine without forcing the two to agree.",
      "The puppy scene carries a little of that feeling. The world does not stop to explain itself. For a moment, I am left without an interpretation.",
      "I would like to remain there for another beat or so. Not because the past was wiser, or because strangeness is automatically profound. I simply like the possibility of meeting an old story without immediately asking it to become me.",
      "To let its gods remain gods. To let the sea remain the sea."
    ]
  },
  {
    "title": "Strange enough to notice",
    "slug": "strange-enough-to-notice",
    "date": "August 5, 2026",
    "readingTime": "3 minutes",
    "paragraphs": [
      "On an unusually warm weekday in April, I committed a small crime of opportunity.",
      "I was between projects—the quiet side of a feast-or-famine business—and work had not claimed the day yet. Before it could, I ran for it, driving north to Minnewaska State Park Preserve. I knew parts of Severance had been filmed there, that was enough of a plan.",
      "I like road trips, being outside, and finding places close to home that I have somehow missed. I was also curious about the show’s outdoor world: bleak, Gothic, slightly unreal. I wanted to see how much of that feeling belonged to the locations themselves.",
      "At the gate, I paid the ranger. I saw a three tourists in the lodge. After that, no one.",
      "Minnewaska has absolutely no shortage of dense forests or dizzying cliffs. There is only one breathtaking waterfall however. I hiked down to it with the fun feeling that I had borrowed the whole preserve for the afternoon.",
      "I expected it to feel eerie there because of the show. It didn’t. It felt quiet and restorative. The place was beautiful, but it had clearly not been waiting around to be Severance. The color, framing, weather, and story had done much of that work.",
      "I liked discovering the gap between the real place and the fictional one. At one of the locations, I could see several paths a camera might have taken. There was no inevitable shot sitting there. Someone had walked around, looked at the rocks and water, and decided what the place could become.",
      "That made the scene more interesting to me, not less. It reminded me that looking is not simply finding the unusual thing. Sometimes it is noticing an unusual possibility inside something that already exists.",
      "I didn’t have a single fixed objective for the day. I wanted to get out of my routine and let things happen. This is usually a good enough reason for me to go somewhere.",
      "I try to find a small edge (not a cliff) I am slightly reluctant to cross. Take an unclaimed weekday. Drive without much of a plan. Walk alone. Step across the water. One edge tends to lead to another.",
      "Chance matters in my work for the same reason. I bring in another person, an unfamiliar reference, a random constraint, or AI because I want something to enter that I couldn’t have planned by myself.",
      "On a cover design for the Las Vegas Sands, I was looking for a natural image that could sit beside an architectural detail with a curling form. AI produced a picture of fiddleheads. Strangely, their curves mirrored the architecture and accidentally formed an S, for Sands.",
      "I would not have planned it, but I still had to notice it. Chance can place something in front of me. It can’t make me care or decide what to do with it. But if I'm open to it, can go to a park, walk to a waterfall, and come home, having a day strange enough to notice things."
    ]
  },
  {
    "title": "The Work Between the Work",
    "slug": "the-work-between-the-work",
    "date": "August 5, 2026",
    "readingTime": "3 minutes",
    "paragraphs": [
      "Some of the most useful work I do leaves almost nothing behind.",
      "It happens in the question that changes the brief, the conversation before the meeting, or the note that explains why a decision was made.",
      "I think of this as the work between the work.",
      "A portfolio makes design look fairly orderly. There is a report, an identity, a platform, or a system. Each one appears to be a self-contained object.",
      "The actual project is usually messier. It includes people, budgets, old decisions, new anxieties, unclear language, and deadlines that do not care whether the idea is ready.",
      "For a long time, I treated all of this as the part surrounding the design. The real work was the thing I could see. I do not think that anymore.",
      "A good idea can fail because it was introduced at the wrong moment, separated from its reason, or handed to someone without enough context to continue it. An ordinary idea can improve because someone asked the right question early enough.",
      "A lot of this work is translation.",
      "Someone asks for more impact. They may mean contrast, confidence, or a clearer sense of what matters first. They may simply be worried that no one will pay attention.",
      "The request is rarely the whole request.",
      "I try to listen for the concern underneath the words. Naming it can save a surprising amount of time. More importantly, it can keep everyone from carefully solving the wrong problem.",
      "Sequence matters too. Rough work shown as finished will be judged badly. Finished work presented as an open question can be pulled apart for no useful reason.",
      "After an important conversation, I usually write down what was decided, why it was decided, and what remains open. The file remembers what changed. It rarely remembers why.",
      "This became more noticeable as I started leading projects. At the end of some days, I had made very little myself. I had clarified a decision, connected two people, protected time for an idea, or removed an obstacle.",
      "At first this felt suspiciously unlike work.",
      "Now I see it as part of making the conditions for good work. It is not automatically valuable. A full calendar can still be a full calendar.",
      "My test is fairly simple: did this make the problem clearer, prepare a real decision, protect the idea, or make the next step easier for someone else? If not, it was probably just motion.",
      "The work between the work is difficult to show. I notice it indirectly: fewer surprises, calmer handoffs, and decisions that continue to make sense after the meeting is over.",
      "There is not much to put in a portfolio. Just work that holds together a little better."
    ]
  },
  {
    "title": "A System for Looking",
    "slug": "a-system-for-looking",
    "date": "August 5, 2026",
    "readingTime": "3 minutes",
    "paragraphs": [
      "Before I make anything, I look.",
      "This sounds obvious. It took me a while to understand what I meant by it.",
      "I used to confuse looking with collecting. I would open a browser, save fifty images, and call the result research. The collection grew. My understanding did not.",
      "Now I try to begin with a question.",
      "What am I actually trying to understand? What has become so familiar that no one sees it anymore? What does a person need to know, feel, or do—and in what order?",
      "The question does not need to point toward an answer. It only needs to give the looking a shape.",
      "I start near the subject. If I am working on an annual report, I look at annual reports. I need to understand the form before I decide what to do with it.",
      "Then I move farther away.",
      "I might look at newspapers, maps, instruction manuals, or paintings. A newspaper knows how to handle density. A map knows how to hold several scales at once. A painting may know something useful about directing the eye.",
      "I am not looking for a style to borrow. I am trying to notice what something is doing.",
      "When I save a reference, I write down why. The scale makes the ordinary feel important. The repetition creates trust. The awkward pause makes me pay attention.",
      "That sentence is usually more useful than the image. It gives me enough distance to carry the idea somewhere else without copying its appearance.",
      "Then I arrange what I have found and start removing things.",
      "One reference tells me what I like. Several references placed together begin to tell me what I think. The one that does not fit is often worth keeping around. It may be pointing to something the rest of the collection has politely avoided.",
      "Time helps too. I am easily persuaded by novelty and finish. If I leave the references alone for a day, some become less convincing. A few become more interesting.",
      "Eventually I make something, usually before I feel ready. A rough sketch shows whether an observation can survive contact with actual words, scale, and use. Often it cannot. Then I know where to look next.",
      "So the system is not very complicated: begin with a question, look outside the category, name what matters, arrange, remove, make, and look again.",
      "The point is not to build an impressive moodboard. It is to notice enough that a decision becomes easier."
    ]
  }
] as const;
