// Generated from content/pages. Do not edit this file directly.

export const generatedPages = [
  {
    "title": "About",
    "slug": "about",
    "paragraphs": [
      "Thinkinghaus grew out of a habit I didn’t expect to become important.",
      "Through collaborating with AI, I found myself putting half-formed ideas into words, arguing with them, revising them, and gradually getting closer to what I actually meant. My writing stopped feeling like something that came after thinking. It became a way of articulating myself—and of noticing what had been rattling around in my head in the first place.",
      "The writing here tries to move in both directions. I like to experiment with tools, systems, methods, frames, and ways of seeing that help me make work that feels more genuinely mine. But I’m just as interested in people who’ve committed themselves to expressing something in their own particular way. I want to understand their processes, systems, approaches, and perspectives; to meet the work on its own terms; and to see what kind of connection becomes possible when somebody has put enough of themselves into a thing for another person to find them there.",
      "The site is deliberately simple for the same reason. I don’t want publishing to become another project. The less machinery between an idea and the page, the more likely I am to follow it. Enough design to make the words pleasant to encounter, then mostly get out of their way."
    ]
  },
  {
    "title": "Links",
    "slug": "links",
    "paragraphs": [
      "[Hundred Rabbits](https://100r.co/)",
      "Rekka Bellum and Devine Lu Linvega make software, games, books, music, tools, and other things while living aboard a sailboat and thinking seriously about technological resilience. Their line—“That which cannot be repaired is already broken”—has been lodged in my head since I found it.",
      "[A Working Library](https://aworkinglibrary.com/)",
      "Mandy Brown’s ongoing library of reading, work, technology, and thought. The site feels accumulated rather than produced. Books lead to notes, notes lead elsewhere, and the whole thing remains visibly in use.",
      "[Scope of Work](https://www.scopeofwork.net/)",
      "Work in its unusually broad sense: tools, machinery, maintenance, competence, labor, curiosity, and the reasons people become interested in doing difficult things well.",
      "[Low-tech Magazine](https://solar.lowtechmagazine.com/)",
      "A long-running investigation of older technologies, forgotten solutions, energy use, resilience, and the assumption that newer necessarily means better.",
      "The solar-powered website is part of the argument, which I appreciate. A philosophy becomes more interesting when it has to pay its own electricity bill.",
      "[Emily Short](https://emshort.blog/)",
      "Writing about interactive fiction, narrative systems, games, AI, conversation, storytelling tools, and the mechanics hiding underneath all of them.",
      "[Zarfhome](https://eblong.com/)",
      "Andrew Plotkin’s home on the web: interactive fiction, programming, books, games, tools, experiments, archives, and decades of things that seemed worth keeping. I first arrived through his games more than twenty years ago and never really left.",
      "[The Public Domain Review](https://publicdomainreview.org/)",
      "A beautifully curated entrance into the enormous public-domain archive: art, literature, science, diagrams, mysticism, forgotten books, peculiar historical obsessions. A longtime favorite. I rarely leave by the same door I came in.",
      "[Whole Earth Index](https://wholeearth.info/)",
      "The Whole Earth publications, gathered into one enormous searchable archive. Tools, ecology, alternative technology, self-sufficiency, architecture, counterculture, computers, farming, education, the works. A gold mine, although “mine” implies someone has already separated the useful material from the rocks.",
      "[Works That Work](https://worksthatwork.com/)",
      "A magazine about unexpected examples of design and ingenuity, particularly outside the places where professional design culture normally goes looking for them.",
      "[The Simplicity Collective](https://simplicitycollective.com/)",
      "Voluntary simplicity considered as something larger than decluttering: consumption, ecology, community, time, meaning, work, and the question of what “enough” means.",
      "[The Center for Land Use Interpretation](https://clui.org/)",
      "Infrastructure, industrial sites, strange boundaries, extraction, transportation, military landscapes, overlooked structures—the ordinary physical evidence of what a society actually does, rather than what it says it does.",
      "[Marginalia Search](https://marginalia-search.com/)",
      "An independent search engine built to surface the smaller, older, stranger, more text-heavy web. Finding this felt less like discovering another search engine than finding a side entrance that had accidentally been left unlocked.",
      "[Kagi Small Web](https://kagi.com/smallweb/)",
      "A stream of writing from independent sites around the web. Addictive.",
      "[Tiny Awards](https://tinyawards.net/)",
      "An annual celebration of small, handmade, independent websites. This can mean an extraordinarily thoughtful political visualization. It can also mean rotating sandwiches.",
      "-----",
      "This page owes its basic idea to [47nil’s links page](https://47nil.com/links)."
    ]
  }
] as const;
