// Generated from content/pages. Do not edit this file directly.

export const generatedPages = [
  {
    "title": "About",
    "slug": "about",
    "paragraphs": [
      "Thinkinghaus is a place for notes on attention, work, and the occasional strange thing.",
      "It is written by Max Pfennighaus.",
      "You can [say hello](mailto:hello@thinking.haus)."
    ]
  },
  {
    "title": "Links",
    "slug": "links",
    "paragraphs": [
      "Things I want to find again."
    ]
  }
] as const;
