// Generated from content/posts. Do not edit this file directly.

export const generatedPosts = [
  {
    "title": "Look at this",
    "slug": "look-at-this",
    "date": "July 7, 2026",
    "readingTime": "5 minutes",
    "paragraphs": [
      "It’s [1932](https://www.nationalgeographic.com/history/article/australian-emu-war-history) and Jean-Paul Sartre and Simone de Beauvoir meet their pal Raymond Aron at the Bec-de-Gaz bar on the rue Montparnasse. Aron had recently been in Berlin, where he’d encountered the philosophy of a certain Mr. Edmund Husserl who had this crazy new thing he was calling phenomenology. As Sarah Bakewell [tells the story](https://search.worldcat.org/de/title/974495411), Aron pointed at the drink in front of him and basically told Sartre that with phenomenology you could make philosophy *out of this cocktail.*",
      "Sartre was absolutely electrified. He got himself over to Berlin to study this stuff for himself, and voilà! phenomenology becomes a major foundation from which his own philosophy was built.",
      "I love this story because it humiliates philosophy juuuust enough. Aron doesn’t begin with Being, or Truth, or the Soul. He points at booze on the table.",
      "It’s easy to hear this as a promise to make philosophy more accessible, as though phenomenology were saying: oh don’t worry, *we* can use relatable examples. But that’s not really what’s interesting about it. The cocktail isn’t an example pasted onto the philosophy afterward. The encounter with the drink is where the philosophy begins, which is a much stranger proposition.",
      "I have a habit of assuming that serious thought lives at some higher altitude. If we want to think about something deeply enough, we must ascend out of the café and start looking for those inscrutable forces bearing capital letters: Meaning, Consciousness, Freedom, Art, God, Reality. Meanwhile the glass is still sitting there sweating onto the table.",
      "One thing phenomenology says is to pay very close attention to experience as it’s actually lived. Not merely hey that’s an object over there, but the experience of perceiving it, remembering it, wanting it, recoiling from it, recognizing it. Husserl gets considerably more complicated than staring down cocktails, obviously. But the concept that smacked Sartre so hard from this experience was that experience itself could be philosophically inexhaustible.",
      "What exactly is this cocktail before I file it away under “cocktail?” Well…there’s color, which I recognize as apricot even though…hmm…I’m not entirely sure apricot is a *color*. There’s the cold glass in my hand. Sweetness arriving before bitterness. My expectation of what it will taste like. The café around it. The fact that I’m sitting with these particular people. One of them is watching me drink it, etc. All these memories and preferences and tiny private histories that have somehow become involved in this otherwise innocent beverage.",
      "Naming things is useful, but it also shrink-wraps them. Cocktail. Café. Friend. Stranger. Job. Website. [Tree](https://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:534145-1/images). Myself. Once something has a name, it becomes very easy to stop encountering it. We know what that is. Move along. The world becomes incredibly efficient and navigable this way, and also slightly dead.",
      "To me there are actually two encounters happening at that table. Sartre is encountering the cocktail differently, but he’s also encountering Aron: somebody who had gone somewhere, found something that rearranged the furniture in his head, and come back excited enough to try to make his friends see what he’d seen.",
      "Aron didn’t hand Sartre a book or paper or give him an academic lecture. He looked around the table, found the nearest available object, and said, essentially: *this*.",
      "There’s something I recognize in that. Some of the most important things I’ve learned from people have arrived badly packaged. A friend gets completely obsessed with a book and starts explaining it before he quite knows how. Someone sends a link saying OMGGGG!!!!!!!  You visit somebody’s house and notice the [fascinating little system](https://www.anitraroweschulte.com/blog/johanna) they’ve developed for doing something you’d never previously considered a system at all. Another person has been paying attention somewhere you haven’t, and for a moment you get to borrow their eyes.",
      "The idea totally matters, but so does the enthusiasm. There’s a kind of intellectual friendship in which people don’t simply exchange conclusions…they infect one another with attention. You become interested because somebody you trust has become interested, and their interest is specific enough that you can get utterly electrified by proxy.",
      "I think this is a piece of why Bakewell’s account of existentialism starts here. Existentialism wasn’t produced by a bunch of isolated genius brains emitting a stream of books. It developed among friendships, love affairs, arguments, rivalries, cafés, letters, teachers, students, and people enthusiastically mangling one another’s ideas.",
      "[Origin stories](https://www.dc.com/blog/2025/04/07/digging-up-the-resurrection-man) are suspiciously tidy, of course. Intellectual movements aren’t born on a table one afternoon any more than rivers begin beneath signs saying [RIVER](https://www.whanganui.govt.nz/Community-and-Places/About-Whanganui/Our-District/Te-Awa-Tupua-Whanganui-River-Settlement) STARTS HERE. Sartre already had his own philosophical ambitions. Husserl had spent decades developing phenomenology. Other thinkers were shooting those ideas all over Europe. I think the legend survives because it compresses something messier into a scene you can hold.",
      "The exchange over the drink seems almost embarrassingly small compared with what followed: Sartre, Beauvoir, existentialism, Being and Nothingness, decades of argument about freedom, consciousness, responsibility, and what the hell we’re all doing here. But that’s exactly what I like about it. The big thing doesn’t arrive as a big thing. It arrives as your friend leaning across a café table and saying: look at this."
    ]
  },
  {
    "title": "The silent type",
    "slug": "a-pretty-normal-typeface",
    "date": "July 1, 2026",
    "readingTime": "2 minutes",
    "paragraphs": [
      "Untitled Sans began as an attempt to make another typeface plainer.",
      "Kris Sowersby removed some of its more noticeable details, got a little lost and put the project away, came back to it several years later, and nearly threw it out. It was only after [reading about](https://khole.net/issues/youth-mode/) the [Super Normal project](https://jaspermorrison.com/exhibitions/2000-2009/super-normal) that he found a way to understand the thing he’d already been making: maybe being deliberately ordinary was enough of a reason for a typeface to exist.",
      "I love that the explanation arrived late in the game, I can identify. I try things. I change my mind. I forget why I started. I wander into something better. Occasionally I understand what I was doing after I’ve already done it.",
      "Sowersby describes deliberately removing traces of his own recognizable style from the letters, scrubbing his fingerprints off the [crime scene.](https://www.btp.police.uk/police-forces/british-transport-police/areas/about-us/about-us/our-history/crime-history/great-train-robbery/?utm_source=chatgpt.com)",
      "That sounds almost perverse for a designer. We’re encouraged to make things distinctive, ownable, memorable—something that can stand up in a presentation and explain why it deserves to exist.",
      "But most of the time, when I’m reading, I don’t need the typeface to introduce itself. I need it to help me *read*.",
      "That’s probably why Untitled Sans feels right for both my [portfolio](http://maxpfennig.haus/) and for Thinkinghaus. The work and the writing can wander around and follow unusual ideas. The letters stay put.",
      "Its plainness isn’t an absence of design. It’s what happens when a mountain of small decisions are made thoughtfully enough that they can recede. The type makes some room around the words instead of elbowing them for attention.",
      "I find that deeply appealing: work that has clearly been thought about, but doesn’t make you stop every five minutes to admire how much thinking went into it.",
      "Work that knows how to be quiet."
    ],
    "source": {
      "label": "Read Kris Sowersby’s notes on the Untitled Collection",
      "href": "https://klim.co.nz/blog/untitled-sans-serif-design-information/"
    }
  },
  {
    "title": "The gift of an empty mind",
    "slug": "the-usefulness-of-an-empty-mind",
    "date": "June 28, 2026",
    "readingTime": "3 minutes",
    "paragraphs": [
      "One of my favorite books—favorite manuals, really—is *Zen Mind, Beginner’s Mind* by the Zen monk Shunryu Suzuki.",
      "He says, “In the beginner’s mind there are many possibilities, in the expert’s, there are few.”",
      "Expertise is darn useful. It recognizes patterns, avoids old mistakes, knows which details matter. But it can also become a kind of compression. The more I know about something, the easier it is to see the category before I see the thing itself.",
      "Suzuki isn’t asking us to become stupid. Beginner’s mind isn’t the absence of knowledge or experience. It’s a way of standing inside what you know without letting your shoes turn to cement. I find this much harder than it sounds.",
      "The book is assembled from talks and still feels spoken. Ideas appear, disappear, return slightly changed. Sometimes an explanation leaves me less certain than I was when it began, which seems appropriate.",
      "Suzuki talks about posture, breathing, repetition, effort, and the very ordinary difficulty of sitting still. The spiritual life he describes is physical. It’s in my hands, my spine, my breath, and my willingness to sit there without turning the whole thing into another achievement.",
      "This is a problem for me because I like practices that produce results. I want to know if I’m progressing. I want a little dashboard somewhere telling me my Zen is up 14 percent from last quarter. Even when I’m actively trying to become less ambitious, I can become ambitious about becoming less ambitious.",
      "Suzuki keeps returning to the activity itself. Sit because you’re sitting. Breathe because you’re breathing. Do the thing without constantly climbing outside it to ask what it means, whether it’s working, and what all of this says about you.",
      "I can’t say I consistently live that way. But I’ve come to value the freedom in it, and meditation gives me a place to practice it. Sometimes I notice how quickly I’ve decided who another person is, what something means, who’s right, who’s ridiculous. Occasionally I can catch myself before the judgment hardens and look again.",
      "That may be what beginner’s mind means to me now. Not becoming innocent again, and certainly not forgetting what I’ve learned. Just setting it down for a minute. Loosening my grip long enough for something I wasn’t expecting to get in.",
      "The joke, of course, is that I can immediately turn this into another thing to master. A program for becoming exceptionally good at having no ambitions about becoming exceptionally good.",
      "*Zen Mind, Beginner’s Mind* doesn’t make Zen easy. It makes simplicity seem like enough to work on."
    ],
    "source": {
      "label": "Read Zen Mind, Beginner’s Mind",
      "href": "https://search.worldcat.org/title/1137753173"
    }
  }
] as const;
