// Generated from content/pages. Do not edit this file directly.

export const generatedPages = [
  {
    "title": "About",
    "slug": "about",
    "paragraphs": [
      "The name makes Thinkinghaus sound more organized than it is.",
      "This is mostly a place for things I can’t quite stop looking at: people, websites, books, movies, places, tools, ideas, design, odd communities, things somebody has been making for thirty years, and whatever else seems worth paying attention to for a little longer than necessary.",
      "I’m a designer, so design will inevitably show up here. Sometimes it’ll even be the whole subject. But Thinkinghaus isn’t a design blog, and I don’t particularly want every walk, book, strange website, or spiritual experience to eventually explain what it taught me about creativity. Some things can just be themselves.",
      "What I’m trying to practice here is something closer to beginner’s mind: encountering a thing before everything I already know tells me what it is. I’m not especially good at this. Expertise, taste, politics, irritation, and ego are all remarkably quick on their feet. But I’ve found that when I can get them out of the doorway for a minute, the world usually gets more interesting.",
      "I’m especially drawn to places where you can feel another person on the other side. Personal websites. Niche cultures. Long-running obsessions. People who are really, genuinely into something. Not because outsiders are automatically right, handmade things are automatically good, or sincerity excuses anything. It doesn’t. I just like encountering the shape of somebody else’s attention.",
      "Sometimes that produces admiration. Sometimes criticism. Sometimes I find something I strongly disagree with and want to understand how anybody got there. The hope is to stay interested long enough that judgment isn’t the only thing I bring home.",
      "The site is simple on purpose. Not because white space is more virtuous than color or because I’ve taken vows in some austere typographic monastery. I want as little machinery as possible between finding something interesting, thinking about it, and putting it somewhere another person can encounter it. The emptiness leaves room for whatever happens to arrive next.",
      "That also keeps the place provisional. I don’t want Thinkinghaus to become a persona I have to protect. I expect to contradict myself, change my mind, get things wrong, write something very serious beside something completely unnecessary, and occasionally wonder why I thought any of this was a good idea.",
      "These pieces are developed in collaboration with AI. That collaboration can involve long conversations, questions, research, argument, interpretation, drafting, and revision. I don’t think authorship is usefully reduced to who physically typed each sentence. The more important questions for me are whose encounter with the world this is, whether the ideas feel like mine, and whether I’m willing to take responsibility for them. If I’m not, we keep working.",
      "There isn’t a particularly grand objective beyond making something worth encountering. Maybe it’s useful. Maybe it produces understanding, wonder, delight, friction, laughter, or a question that sticks around. Maybe it’s just a good link you wouldn’t have found otherwise.",
      "Leave the place a little better than you found it, then keep looking."
    ]
  },
  {
    "title": "Links",
    "slug": "links",
    "paragraphs": [
      "Places I return to, things I’ve recently discovered, and corners of the internet I don’t want to lose.",
      "This isn’t a canon and it’s definitely not an endorsement of every idea contained inside. They’re here because something about them made me want to keep looking.",
      "[Cabinet](https://cabinetmagazine.org/)",
      "A magazine built on the pleasant assumption that almost anything becomes interesting if you look at it hard enough. Extremely good at wandering across the borders between art, science, history, objects, and ideas without worrying too much about which department owns them.",
      "[Emily Short](https://emshort.blog/)",
      "I met Emily briefly years ago, but I’d already known her through interactive fiction. Her writing about narrative systems, characters, games, and how stories actually behave has been a rabbit hole for me ever since.",
      "[Hundred Rabbits](https://100r.ca/)",
      "Rekka and Devine live and work aboard a sailboat, making software, tools, games, drawings, manuals, and an ongoing record of how they live. Their line “That which cannot be repaired is already broken” has been stuck in my head. This feels lived rather than lifestyle-branded.",
      "[The Center for Land Use Interpretation](https://clui.org/)",
      "A research organization devoted to noticing what we’ve done with the land. Missile ranges, mines, infrastructure, waste sites, water systems, borders. The places we usually drive past become very strange once somebody actually points at them.",
      "[Marginalia Search](https://search.marginalia.nu/)",
      "An independent search engine built to surface the small, text-heavy, noncommercial web that larger search engines tend to bury. I started using it after putting this page together and now visit it constantly. Search that still feels a little like wandering.",
      "[Tiny Awards](https://tinyawards.net/)",
      "An annual celebration of small, handmade, noncommercial websites. I’m obsessed with the range: serious political work sitting a few clicks away from somebody who decided the internet needed a rotating sandwich. Correct.",
      "[The Public Domain Review](https://publicdomainreview.org/)",
      "An old favorite. Strange books, forgotten illustrations, scientific diagrams, photographs, occult material, marginalia, and whatever else has escaped copyright and wandered into the commons. Almost irresponsibly easy to lose an afternoon here.",
      "[Whole Earth Index](https://www.wholeearth.info/)",
      "A nearly complete archive of the publications that grew out of the Whole Earth Catalog. Self-sufficiency, alternative technology, counterculture, tools, education, ecology, and several decades of people asking what might be possible if they did things differently. A gold mine.",
      "[Scope of Work](https://www.scopeofwork.net/)",
      "Spencer Wright’s long-running writing about manufacturing, engineering, infrastructure, maintenance, and the physical world. I like how seriously it takes the people who actually know how things get built and kept running.",
      "[Works That Work](https://worksthatwork.com/)",
      "A finished magazine, which is perhaps part of its charm now. “Unexpected creativity” was its territory: the ingenuity buried inside ordinary systems, objects, communities, and places rather than design as a parade of expensive chairs.",
      "[Low-tech Magazine](https://solar.lowtechmagazine.com/)",
      "Research into older, simpler, overlooked ways of solving problems, published on a website designed around the same questions. I especially like projects where the philosophy leaks into the plumbing.",
      "[A Working Library](https://aworkinglibrary.com/)",
      "Mandy Brown reading across books, technology, work, politics, and whatever else attaches itself along the way. The library is “working” in the literal sense: one thing gets connected to another and starts producing new thought.",
      "[The Simplicity Collective](https://www.simplicitycollective.com/)",
      "An earnest, unfashionably serious exploration of living with less in a culture built around wanting more. I don’t need every conclusion to land for me to appreciate somebody actually asking the question at full volume.",
      "[Kagi](https://kagi.com/)",
      "A search engine you pay for instead of one financed by selling your attention. More importantly, it’s just a much nicer way to search: tunable, quiet, and unusually good at getting me somewhere useful. This became a daily visit almost immediately."
    ]
  }
] as const;
