import { writeFile } from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { displayDate, projectRoot, readPages, readPosts } from "./content.mjs";

export async function generatePostsModule() {
  const posts = (await readPosts()).map((post) => ({
    title: post.title,
    slug: post.slug,
    date: displayDate(post.date),
    readingTime: post.readingTime,
    paragraphs: post.paragraphs,
    ...(post.source ? { source: post.source } : {}),
  }));

  const output = `// Generated from content/posts. Do not edit this file directly.\n\n` +
    `export const generatedPosts = ${JSON.stringify(posts, null, 2)} as const;\n`;

  await writeFile(path.join(projectRoot, "app", "generated-posts.ts"), output, "utf8");

  const pages = (await readPages()).map((page) => ({
    title: page.title,
    slug: page.slug,
    paragraphs: page.paragraphs,
  }));
  const pagesOutput = `// Generated from content/pages. Do not edit this file directly.\n\n` +
    `export const generatedPages = ${JSON.stringify(pages, null, 2)} as const;\n`;
  await writeFile(path.join(projectRoot, "app", "generated-pages.ts"), pagesOutput, "utf8");
  return posts;
}

if (
  process.argv[1] &&
  import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href
) {
  const posts = await generatePostsModule();
  console.log(`Generated ${posts.length} published post${posts.length === 1 ? "" : "s"}.`);
}
